sudo: required
dist: trusty
cache:
- apt
- ccache
language: generic
compiler:
- gcc
env:
  global:
  - CATKIN_WS=~/catkin_ws
  - CATKIN_WS_SRC=${CATKIN_WS}/src
  - CI_ROS_DISTRO="indigo"
  - secure: "smFIa1qA533FrLwuCW9AtegXk2bs0C2swDJWXWAikCSgET+fpF7DsGXAeE407PeZQBodnG/ZO3BODyE8orNvszBsNlK0QUx68kp8V2fgicg1V/PqlfhhUCNAZlhnI2xas/dZhvl4Ao8rfY1GZlyfms279yJljGdnVFiEyqQzQtiIN/komwpZKT7flTon9RrZ7QK5+N0nHA+17mX9Nl0L7H+pd2h3vBd7Wz4eb5S8O14zeuTcMcxlxJb8WP4W5KvHIwmiWFluhFamedc45LVXhJb0gECm7nNx1Qyrf1MQdRlBlWJ16AaxmHgdmiONQrc0/U7L2zs7aUfedJC9lmxTwCcQSTrdbO27e4nnb4VPptXITtGM2/8yn+m1pQzRNyJbrCcQyRilPPSRfhrQ24oaiingOATH+BCJ/sTkZTB8/9qjcMXkk7zPIMHTjGwonvyot33ftwlLMmu3pwm23dHcTttuEBlAjngDIarWhEFhZwvO6N9/vp478b1RJpFzDUgIZsbZWA3w6JjSkl49jXjLVn9ni5ciIs6rA6jo9MnVlVN9uLqOdJiavLRuakt6B2bzoU8Ghmz8JpcaBdRG2LhLb1HDCFdMehnTmmpcrQoUAgW6mQxJvUt1GV7LsODR1vhCb+zDh30zbCSKDDZQLjiQOMb1DAv7qrnfr+4MDkcxLbk="
before_install:
- wget https://bitbucket.org/eigen/eigen/get/3.2.6.zip
- unzip 3.2.6.zip
- cd eigen-eigen-c58038c56923
- mkdir build
- cd build
- cmake ..
- sudo make install
- cd ../..
install:
- sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu trusty main" > /etc/apt/sources.list.d/ros-latest.list'
- wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
- sudo apt-get update -qq
- sudo apt-get install -qq -y python-rosdep python-catkin-tools
- sudo rosdep init
- rosdep update
- rosdep install --from-paths ./ -i -y --rosdistro $CI_ROS_DISTRO
script:
- source /opt/ros/$CI_ROS_DISTRO/setup.bash
- mkdir -p $CATKIN_WS_SRC
- ln -s $TRAVIS_BUILD_DIR $CATKIN_WS_SRC
- cd $CATKIN_WS_SRC
- catkin_init_workspace
- cd ..
- catkin_make install -DCMAKE_BUILD_TYPE=Release -j4
before_deploy:
- bash $TRAVIS_BUILD_DIR/.ci_after_success.sh
# Create git tag
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
#- export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d")-$TRAVIS_BUILD_NUMBER
- cd $TRAVIS_BUILD_DIR
- export GIT_TAG=latest
- git push https://$GITHUBKEY@github.com/openhumanoids/exotica :refs/tags/$GIT_TAG
- git tag $GIT_TAG -a -m "Updated tag latest from build $TRAVIS_BUILD_NUMBER" -f
- git push --quiet --tags https://$GITHUBKEY@github.com/openhumanoids/exotica $GIT_TAG > /dev/null 2>&1
branches:
  except:
    - /^build-[0-9a-z\-]*/
    - /^latest*/
deploy:
  provider: releases
  api_key:
    secure: Q5HEVWeizz926t9snRXDsh/rZvYq1Cno6fe9vSdDf8H1FRVyjD5HyOAuvlb5Aawdwzi37oGx+oWQvVUkjNAziLke/pBaW6ni1pdvTxiLWXJCAQawxEtnum1leqqOA7U2zz4ufpTxrCw9ss+f2qcKQP3O3B0DjK7EcsjflBsAz5gAGcut6FAv77pzp6KToKSeKrFuheWTHnoL3r+UXT8WO3Lw82sH1rISosP7SBuumLqcT1TIWoYEdnLgnzFcaKkXDTQW9/2VP8drBR57HsbKj6IplgRoOmXjOREgrgRoQ4hhVi1Zoq8ia9CWa7k7w7WUWqpoHq0MwzMab07nWZBcTw6vGki2d5tGmykHTU+TM8rVRZzOS7uUjnJNUM+5yoWt6IE2PCI6jdJpRH2ZU50BwGVx7etYl8sgQQDL1gdZKBjEWX8cdOCj4aPiCxuuoiTTggI1wvG3UmSUUUA3XIk5hAQ1B5e5fsKcpAluouOWulCYoyS+agK/sZVHyMwiaDSp2ddaRuZmtaJMRWtmOU5IUP89EiJWCqSj9ZY89gp1TPD6+1hmlXOr25K7N83ez3/8aGLHSV7my5gr5fCTpLCe9/3HO7Y+L/7xw0JHtsdxdJ/S4XSK5as+TQEY9QiDNlG0xEsv/g6o7CU3ns0qfM3y+BuoqSY2unyhlRsyL9YjPm4=
  skip_cleanup: true
  file: "exotica.deb"
  on:
    repo: openhumanoids/exotica
    tags: false
    all_branches: true
