# This config file for Travis CI utilizes ros-industrial/industrial_ci package.
# For more info for the package, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst
language: generic
dist: bionic
services:
  - docker

# include the following block if the C/C++ build artifacts should get cached by Travis,
# CCACHE_DIR needs to get set as well to actually fill the cache
cache:
  directories:
    - $HOME/.ccache

git:
  quiet: true # optional, silences the cloning of the target repository

# configure the build environment(s)
# https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst#variables-you-can-configure
env:
  global: # global settings for all jobs
    - CCACHE_DIR=$HOME/.ccache # enables C/C++ caching in industrial_ci
    - ROS_REPO=ros-testing # ros
  matrix:
    - ROS_DISTRO="kinetic" CMAKE_ARGS='-DCMAKE_BUILD_TYPE=Debug' PARALLEL_BUILDS=1
    - ROS_DISTRO="kinetic" CMAKE_ARGS='-DCMAKE_BUILD_TYPE=Release'
    - ROS_DISTRO="kinetic" PRERELEASE=true
    - ROS_DISTRO="kinetic" CLANG_FORMAT_CHECK=file CLANG_FORMAT_VERSION=3.9
    - ROS_DISTRO="melodic" CMAKE_ARGS='-DCMAKE_BUILD_TYPE=Debug' PARALLEL_BUILDS=1
    - ROS_DISTRO="melodic" CMAKE_ARGS='-DCMAKE_BUILD_TYPE=Release'
    - ROS_DISTRO="melodic" PRERELEASE=true
    - ROS_DISTRO="noetic" CMAKE_ARGS='-DCMAKE_BUILD_TYPE=Debug' PARALLEL_BUILDS=1
    - ROS_DISTRO="noetic" CMAKE_ARGS='-DCMAKE_BUILD_TYPE=Release'
    - ROS_DISTRO="noetic" PRERELEASE=true
matrix:
  allow_failures:
    - env: ROS_DISTRO="kinetic" PRERELEASE=true
    - env: ROS_DISTRO="melodic" PRERELEASE=true
    - env: ROS_DISTRO="noetic" PRERELEASE=true
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .ci_config -b master
script:
  - source .ci_config/travis.sh
